### ISSUE TITLE
HELP SYNIURGE!

### ISSUE THREAD

**Issue by Vester1E** [Syniurge/ShieldControllerWinDriver#10]
I've had problem's with this controller driver for so long because the only thing that works is the Trackpad.

When I go to http://html5gamepad.com/ it is recognized as a "NVIDIA Controller v01.03 (STANDARD GAMEPAD Vendor: 0955 Product: 7210)" so it should be recognized but it isn't showing up when I open up Farcry 3, Farcry 4, Farcry Primal or Overwatch.

I have no idea why it isn't working please help!
 From Vester.

**Comment by Syniurge** [comment]
Hi,

Is the gamepad recognized in x360ce?
My README doesn't emphasize it enough, but nowadays most modern games need x360ce to work properly with standard HID gamepads.

If the trackpad works properly (i.e no weird behavior), that means that the driver is probably working, and all you have to do is setup x360ce.
