### ISSUE TITLE
Wrong Hardware ID

### ISSUE THREAD

**Issue by ricsp** [Syniurge/ShieldControllerWinDriver#11]
Hi,
I cannot get windows 10 to use this driver for my controller.
I noticed two things:
1) The controller appears as a mouse pointer in windows device manager
2) The Hardware ID of my controller seems to be HID\VID_0955&PID_7210&REV_0100&Col02 instead of USB\VID_0955&PID_7210.
I tried to change the hardware id to HID\VID_0955&PID_7210&REV_0100&Col02 in the inf file and windows seems to accept the driver but now it still won't install it because (I guess), after the change, the signature does not work anymore.
What can I do?
Thanks and cheers.
Riccardo

**Comment by Syniurge** [comment]
Hi,

This ID of from one of the subdevices. To find the "root" controller device first display devices hierarchically by connection, and then look for a USB input device with these 4 subdevices:
![image](https://user-images.githubusercontent.com/4272771/28999096-8f0cce30-7a11-11e7-984e-a12fa2ad384a.png)

![image](https://user-images.githubusercontent.com/4272771/28999084-4021c21c-7a11-11e7-8dcd-ba27a31f70f9.png)

That said, it's weird that the driver wasn't selected automatically for your controller. But you can select the driver yourself by right-clicking on the "root" controller device (which should have HID\VID_0955&PID_7210&REV_0100 as ID).
