### ISSUE TITLE
How to Uninstall?...

### ISSUE THREAD

**Issue by GANKUTSU-O-TAKU** [Syniurge/ShieldControllerWinDriver#13]
After installation I gamed for a couple of days and then a message popped up with something about the Nvidia Shield Controller touchpad driver needing an update, that failed and my mouse no longer works. I tried everything to fix it but I'm left hoping uninstalling the inf will work. I just have no clue how to undo it...

**Comment by Farewe** [comment]
Have you looked at this conversation?
https://forums.geforce.com/default/topic/951027/shield-tablet/shield-controller-working-in-any-game-on-any-pc-with-new-small-driver/post/5177828/#5177828

**Comment by clementkirton** [comment]
I also want to know how to uninstall it as i was using it and after getting a nvidia gpu now my gamestream with steam is messed up and does not work :/

**Comment by Syniurge** [comment]
I don't think that your issues are related to this driver, but to uninstall, find your gamepad in the device manager (by displaying *devices by connection*), right-click on the root "Shield Controller" device, click "Uninstall..", and check "Uninstall driver" before clicking "OK". This will completely remove the driver from Windows.

Check out the old README if you need help finding your gamepad root device:

https://github.com/Syniurge/ShieldControllerWinDriver/blob/bbc2a3f58fdce4acc12837b01e2ecde7bb55d85d/README.md#installation-and-signing-issue
