### ISSUE TITLE
37 error 

### ISSUE THREAD

**Issue by runnerman2** [Syniurge/ShieldControllerWinDriver#2]
37 error when installing driver,games don't see controller
windows 8.1 intel HD 3000

**Comment by Syniurge** [comment]
Hi and sorry I missed your issue. Did you enable TESTSIGNING? 

Could you try disabling signing checks entirely by following this: https://learn.sparkfun.com/tutorials/disabling-driver-signature-on-windows-8/disabling-signed-driver-enforcement-on-windows-8
(this only lasts until the next restart)

**Comment by runnerman2** [comment]
tried,still the same error,not working

**Comment by Syniurge** [comment]
Alright maybe I need to target an older version of Windows in the WDK build, I'll have a look tonight.

**Comment by runnerman2** [comment]
ok, thanks for your help

**Comment by Syniurge** [comment]
Please redownload the binaries, the driver should now work up to Windows 7 (my DDK doesn't let me target versions older than Win 7).

Thanks for reporting this, as I said in the forum this was the first time I delved into Windows drivers, and wrongly assumed that not using anything specific to the later versions of Windows would make the driver built by Win 10's DDK compatible with Win 8 and earlier.

**Comment by runnerman2** [comment]
thanks,controller working,but touchpad don't work,cursor buggy,he returns
back when i move it

2016-08-02 3:35 GMT+03:00 Elie Morisse notifications@github.com:

**Comment by Syniurge** [comment]
That's weird, does your controller have the latest firmware? Firmware updates are done by the Shield tablet or TV.

**Comment by runnerman2** [comment]
i updated controller when shield tablet is on 5.1.1 , i can't update
controller because my shield tablet is broken

**Comment by runnerman2** [comment]
and without driver touchpad works fine

2016-08-03 14:20 GMT+03:00 Алексей Лапов 42chhk@gmail.com:

> i updated controller when shield tablet is on 5.1.1 , i can't update
> controller because my shield tablet is broken

**Comment by Syniurge** [comment]
Hmm interesting, that explains why some people reported that the trackpad was working out-of-the-box before.

Unfortunately I've no idea how the firmware version is queried and whether it's even possible in USB (and not just Wifi Direct). What I can do is provide you a special build where the trackpad part works like before, it'll be a workaround for older firmwares while the normal build is meant for the latest firmware. I'll do it tonight.

(actually I'm not even sure if this will work, the descriptors may not be the same for older versions. but we'll try and if it doesn't, you could still extract the descriptors yourself in UsbLyzer and send them to me)

**Comment by Syniurge** [comment]
Here's the driver with the trackpad tweaks disabled:

**32 bits:** http://homo-nebulus.fr/shieldcontrollerusbfilter/Old%20firmwares/ShieldControllerDriver_32%20(old%20firmware%20workaround).zip 
**64 bits:** http://homo-nebulus.fr/shieldcontrollerusbfilter/Old%20firmwares/ShieldControllerDriver_64%20(old%20firmware%20workaround).zip

**It still uses the HID report descriptor from the latest firmware**, so there's a chance the trackpad might not work properly either.

**Comment by Syniurge** [comment]
The original issue was fixed, so closing. If you still have trackpad issues you can still comment.
