### ISSUE TITLE
Works fine! but....

### ISSUE THREAD

**Issue by AbramsM1A2** [Syniurge/ShieldControllerWinDriver#3]
But i have questions about the driver.
-Can i turn off the test version of windows 10?
-Vibration on the controller is not working.

Amazing job dude. THX i can play now all titles :D

**Comment by Syniurge** [comment]
Hi! Sorry for the late reply:

> Can i turn off the test version of windows 10?

Windows 64 bits (since Vista iirc, but restrictions have gotten tighter with newer versions) requires drivers to be signed by a certificate validated by Microsoft, and acquiring one costs a few hundred $.

Enabling "test-signed" drivers is harmless as far as I know, and signed drivers aren't necessarily better, more secure, etc. so as far as I'm concerned I can live with the "test mode".

> Vibration on the controller is not working.

Which game? Vibration should at least work in all Xinput games (if you set "Constant force" in x360ce).

For older DirectInput games this is less certain because the driver only exposes "Constant force" effects, while other types of force feedback effect used to exist in DirectInput. But the missing effects could be implemented if needed by a game.

**Comment by AbramsM1A2** [comment]
I am not using x360ce, in a fact i try to configure it, but record mode dont work with the gamepad. Current playing rocket league only with shield controller

**Comment by Syniurge** [comment]
Sorry for the late reply again, in the driver .zip file there's an example x360ce.ini: 

https://github.com/Syniurge/ShieldControllerWinDriver/blob/master/x360ce/x360ce.ini

but the controller ID (IG_7adb3b504db711e58002444553540000) may not be the same as yours. However if you edit your own x360ce.ini file and replace what follows `[IG_7adb3b504db711e58002444553540000]` by the values in the driver's x360ce.ini file, vibration and everything else should work:

```
[IG_7adb3b504db711e58002444553540000]  <- disregard this ID, but copy paste everything below
ProductName=NVIDIA Controller v01.03
ProductGuid=72100955-0000-0000-0000-504944564944
InstanceGuid=7adb3b50-4db7-11e5-8002-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=10
B=9
GuideButton=11
Back=12
Start=1
X=8
Y=7
D-pad POV=1
D-pad Down=d3
D-pad Left=d4
D-pad Right=d2
D-pad Up=d1
UseForceFeedback=1
ForcePercent=100
SwapMotor=0
FFBType=0
ControllerType=1
LeftMotorPeriod=120
LeftMotorStrength=100
LeftMotorDirection=1
Left Shoulder=6
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=x1
Left Analog Y=x-2
Left Thumb=4
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=a4
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=60
RightMotorStrength=100
RightMotorDirection=-1
Right Shoulder=5
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=x3
Right Analog Y=x-6
Right Thumb=3
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=a5
Right Trigger DeadZone=0
A DeadZone=0
B DeadZone=0
Back DeadZone=0
Start DeadZone=0
X DeadZone=0
Y DeadZone=0
Left Thumb DeadZone=0
Right Thumb DeadZone=0
Left Shoulder DeadZone=0
Right Shoulder DeadZone=0
AxisToDPadDownDeadZone=0
AxisToDPadLeftDeadZone=0
AxisToDPadRightDeadZone=0
AxisToDPadUpDeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0
```

**Comment by AbramsM1A2** [comment]
Now i have the buttons configured on x360ce, but still not working vibration in constant with rocket league. And thx for response

**Comment by Syniurge** [comment]
Does vibration work in x360ce when you move the Test sliders in the Force Feedback tab?

**Comment by AbramsM1A2** [comment]
I think that is not working, i move the test up and down and anything happens

**Comment by Syniurge** [comment]
Could you copy paste your entire x360ce.ini file here?

**Comment by AbramsM1A2** [comment]
[Options]
UseInitBeep=1
Log=0
Console=0
DebugMode=0
InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
InternetFeatures=1
InternetAutoload=1
AllowOnlyOneCopy=1
ProgramScanLocations=C:\Program Files,C:\Program Files (x86)
Version=2
CombineEnabled=0
Supplemental=0

[InputHook]
HookMode=1

[Mappings]
PAD1=IG_ecbb3d3dc2ea4861983fb3e15bdc6c52
PAD2=
PAD3=
PAD4=

[PAD1]
[PAD2]
[PAD3]
[PAD4]

[IG_ecbb3d3dc2ea4861983fb3e15bdc6c52]
ProductName=NVIDIA Shield
ProductGuid=b4000955-0000-0000-0000-504944564944
InstanceGuid=ecbb3d3d-c2ea-4861-983f-b3e15bdc6c52
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=10
B=9
GuideButton=11
Back=12
Start=1
X=8
Y=7
D-pad POV=1
D-pad Down=d3
D-pad Left=d4
D-pad Right=d2
D-pad Up=d1
UseForceFeedback=1
ForcePercent=100
SwapMotor=0
FFBType=0
ControllerType=1
LeftMotorPeriod=120
LeftMotorStrength=100
LeftMotorDirection=1
Left Shoulder=6
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=x1
Left Analog Y=x-2
Left Thumb=4
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=a4
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=60
RightMotorStrength=100
RightMotorDirection=-1
Right Shoulder=5
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=x3
Right Analog Y=x-6
Right Thumb=3
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=a5
Right Trigger DeadZone=0
A DeadZone=0
B DeadZone=0
Back DeadZone=0
Start DeadZone=0
X DeadZone=0
Y DeadZone=0
Left Thumb DeadZone=0
Right Thumb DeadZone=0
Left Shoulder DeadZone=0
Right Shoulder DeadZone=0
AxisToDPadDownDeadZone=0
AxisToDPadLeftDeadZone=0
AxisToDPadRightDeadZone=0
AxisToDPadUpDeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0

**Comment by AbramsM1A2** [comment]
maybe i have to reset the controller or something like that, maybe the controller disabled vibration, but its weird. Two weeks ago works fine the vibration. Thx for help

**Comment by AbramsM1A2** [comment]
So i checked the controller on other pc, and vibration works, the other pc dont have the new driver, just the old nvidia geforce.

**Comment by Syniurge** [comment]
At first glance the .ini seems fine, I'll test it tonight.

Is your controller firmware up-to-date?

I just remembered however that the x360ce config tool sometimes doesn't close properly, eats up one CPU core until killed. Check the Task Manager (`Ctrl + Alt + Del`), and kill every x360ce.exe instance. I don't know if that's related to the vibration not working but it's worth a try.

**Comment by AbramsM1A2** [comment]
Yep its up to date, i think is related to the driver. Before the driver instalation vibration was working. And the x360 its not necessary at all. I mean with the program closed i can play all games, just vibration still not working, with or without the x360ce.

**Comment by Syniurge** [comment]
> with or without the x360ce

That means x360ce isn't being used and RocketLeague is selecting DirectInput instead of Xinput. And like many recent games, **rumble is probably only implemented through Xinput**.

x360ce works by generating a `xinput.dll` file (+ the x360ce.ini file) inside the **game executable folder** (make sure that it's the actual game .exe, not a launcher), to override the system's `xinput.dll`. You should hear a _bip_ sound during the game initialization if x360ce is working properly, and Rocket League should detect the controller as a Xbox 360 controller.

Also after some googling Rocket League seems to required additional setup in x360ce:
https://steamcommunity.com/app/252950/discussions/0/496880503082683696/
http://www.pic-upload.de/view-28821717/x360ce.png.html

Good luck, and sorry for replying so late every time, I had a busy week.

**Comment by AbramsM1A2** [comment]
Vibration still not working. But thx for replying everytime. And for your work. Have a nice week.

**Comment by Syniurge** [comment]
Hmm I just noticed that your ProductName is different, meaning we do not have exactly the same controller model revision and/or firmware. I'd be very interested to know if your HID Report Descriptor is the same as mine or not.

If you want me to investigate further why vibration is not working for you and perhaps for others, you need to extract the descriptor with BusDog:
https://github.com/djpnewton/busdog

Install it, run it (restart may be required), unplug your controller, check "Automatically sniff new devices" at the bottom of the Devices tab, then plug your controller. The HID Report Descriptor is the **longest** Hex value (should be around 268 bytes) that should show up in the "Trace" tab.

Then copy the Hex value here.  I think this is the most likely reason why vibration isn't working for you with my driver.

**Comment by AbramsM1A2** [comment]
okay, i hope i did it well, here its the hex values. Sry for late reply

Id  Type    Time    Length  Hex Ascii  
27  In  (USB URB Function: 9)   0.000000    16  01 01 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000112    16  01 01 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000140    16  01 01 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
27  In  (USB URB Function: 9)   0.117845    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000177    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000088    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
27  In  (USB URB Function: 9)   1.785669    16  01 04 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000173    16  01 04 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000086    16  01 04 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
27  In  (USB URB Function: 9)   0.071785    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000064    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000025    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
27  In  (USB URB Function: 9)   2.949871    16  01 20 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 . ..........  
28  R   0.000155    16  01 20 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 . ..........  
28  R   0.000088    16  01 20 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 . ..........  
27  In  (USB URB Function: 9)   0.071685    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000043    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............  
28  R   0.000010    16  01 00 00 0f ff 7f ff 7f ff 7f ff 7f 00 00 00 00 ............
